/* AUTO-GENERATED by scripts/generate-agent-artifacts.mjs. */
import type { AgentUiComponentContract } from './types.js';

export const componentCatalog = [
  {
    "tagName": "ae-accordion",
    "properties": [
      {
        "name": "defaultValue",
        "attribute": "default-value",
        "type": "string[]"
      },
      {
        "name": "expanded",
        "attribute": "expanded",
        "type": "string[]"
      },
      {
        "name": "multiselectable",
        "attribute": "multiselectable",
        "type": "boolean"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string[]"
      }
    ],
    "events": [
      {
        "name": "ae-accordion-change",
        "type": "CustomEvent<{value: string[]}>"
      },
      {
        "name": "ae-expand-change",
        "type": "CustomEvent"
      }
    ]
  },
  {
    "tagName": "ae-accordion-item",
    "properties": [
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "headerId",
        "attribute": "header-id",
        "type": "string"
      },
      {
        "name": "open",
        "attribute": "open",
        "type": "boolean"
      }
    ],
    "events": [
      {
        "name": "ae-accordion-item-change",
        "type": "CustomEvent<{headerId: string, open: boolean}>"
      },
      {
        "name": "ae-panel-change",
        "type": "CustomEvent<{headerId: string, open: boolean}>"
      }
    ]
  },
  {
    "tagName": "ae-alert",
    "properties": [
      {
        "name": "closable",
        "attribute": "closable",
        "type": "boolean"
      },
      {
        "name": "open",
        "attribute": "open",
        "type": "boolean"
      },
      {
        "name": "size",
        "attribute": "size",
        "type": "'sm' | 'md' | 'lg'"
      },
      {
        "name": "variant",
        "attribute": "variant",
        "type": "'info' | 'success' | 'warning' | 'error'"
      }
    ],
    "events": [
      {
        "name": "ae-close",
        "type": "CustomEvent"
      }
    ]
  },
  {
    "tagName": "ae-autocomplete",
    "properties": [
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string"
      },
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "maxItems",
        "attribute": "max-items",
        "type": "number"
      },
      {
        "name": "minChars",
        "attribute": "min-chars",
        "type": "number"
      },
      {
        "name": "options",
        "attribute": "options",
        "type": "(string|AutocompleteOption)[]"
      },
      {
        "name": "placeholder",
        "attribute": "placeholder",
        "type": "string"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-autocomplete-change",
        "type": "CustomEvent<{value: string, option: AutocompleteOption|null}>"
      },
      {
        "name": "ae-autocomplete-select",
        "type": "CustomEvent<{value: string, option: AutocompleteOption}>"
      }
    ]
  },
  {
    "tagName": "ae-badge",
    "properties": [
      {
        "name": "closable",
        "attribute": "closable",
        "type": "boolean"
      },
      {
        "name": "dot",
        "attribute": "dot",
        "type": "boolean"
      },
      {
        "name": "outline",
        "attribute": "outline",
        "type": "boolean"
      },
      {
        "name": "size",
        "attribute": "size",
        "type": "'sm'|'md'|'lg'"
      },
      {
        "name": "variant",
        "attribute": "variant",
        "type": "'primary'|'secondary'|'success'|'warning'|'error'|'info'"
      }
    ],
    "events": [
      {
        "name": "ae-badge-close",
        "type": "CustomEvent<void>"
      }
    ]
  },
  {
    "tagName": "ae-breadcrumb",
    "properties": [
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string"
      },
      {
        "name": "separator",
        "attribute": "separator",
        "type": "string"
      }
    ],
    "events": []
  },
  {
    "tagName": "ae-breadcrumb-item",
    "properties": [
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string"
      },
      {
        "name": "current",
        "attribute": "current",
        "type": "boolean"
      },
      {
        "name": "href",
        "attribute": "href",
        "type": "string"
      }
    ],
    "events": []
  },
  {
    "tagName": "ae-button",
    "properties": [
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "iconOnly",
        "attribute": "icon-only",
        "type": "boolean"
      },
      {
        "name": "iconPosition",
        "attribute": "icon-position",
        "type": "'start' | 'end'"
      },
      {
        "name": "size",
        "attribute": "size",
        "type": "'sm' | 'md' | 'lg'"
      },
      {
        "name": "unstyled",
        "attribute": "unstyled",
        "type": "boolean"
      },
      {
        "name": "variant",
        "attribute": "variant",
        "type": "'primary' | 'secondary' | 'ghost'"
      }
    ],
    "events": [
      {
        "name": "ae-button-click",
        "type": "CustomEvent<{sourceEvent: Event}>"
      }
    ]
  },
  {
    "tagName": "ae-checkbox",
    "properties": [
      {
        "name": "checked",
        "attribute": "checked",
        "type": "boolean"
      },
      {
        "name": "defaultChecked",
        "attribute": "default-checked",
        "type": "boolean"
      },
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "indeterminate",
        "attribute": "indeterminate",
        "type": "boolean"
      },
      {
        "name": "name",
        "attribute": "name",
        "type": "string"
      },
      {
        "name": "required",
        "attribute": "required",
        "type": "boolean"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-checkbox-change",
        "type": "CustomEvent<{checked: boolean, indeterminate: boolean}>"
      }
    ]
  },
  {
    "tagName": "ae-combo",
    "properties": [
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string"
      },
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "freeInput",
        "attribute": "free-input",
        "type": "boolean"
      },
      {
        "name": "items",
        "attribute": "items",
        "type": "(string|ComboItem)[]"
      },
      {
        "name": "placeholder",
        "attribute": "placeholder",
        "type": "string"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-combo-input",
        "type": "CustomEvent<{value: string}>"
      },
      {
        "name": "ae-combo-select",
        "type": "CustomEvent<{value: string, item: ComboItem | null}>"
      }
    ]
  },
  {
    "tagName": "ae-drawer",
    "properties": [
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string | null"
      },
      {
        "name": "backdrop",
        "attribute": "backdrop",
        "type": "boolean"
      },
      {
        "name": "closable",
        "attribute": "closable",
        "type": "boolean"
      },
      {
        "name": "open",
        "attribute": "open",
        "type": "boolean"
      },
      {
        "name": "placement",
        "attribute": "placement",
        "type": "string"
      },
      {
        "name": "size",
        "attribute": "size",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-drawer-close",
        "type": "CustomEvent<void>"
      },
      {
        "name": "ae-drawer-open",
        "type": "CustomEvent<void>"
      }
    ]
  },
  {
    "tagName": "ae-dropdown",
    "properties": [
      {
        "name": "defaultOpen",
        "attribute": "default-open",
        "type": "boolean"
      },
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "header",
        "attribute": "header",
        "type": "string"
      },
      {
        "name": "open",
        "attribute": "open",
        "type": "boolean"
      },
      {
        "name": "placement",
        "attribute": "placement",
        "type": "| 'top'\n  | 'top-start'\n  | 'top-end'\n  | 'bottom'\n  | 'bottom-start'\n  | 'bottom-end'\n  | 'left'\n  | 'left-start'\n  | 'left-end'\n  | 'right'\n  | 'right-start'\n  | 'right-end'"
      },
      {
        "name": "strategy",
        "attribute": "strategy",
        "type": "'absolute' | 'fixed'"
      },
      {
        "name": "theme",
        "attribute": "theme",
        "type": "'light' | 'dark'"
      }
    ],
    "events": [
      {
        "name": "ae-open-change",
        "type": "CustomEvent"
      },
      {
        "name": "ae-select",
        "type": "CustomEvent<unknown>"
      }
    ]
  },
  {
    "tagName": "ae-dropdown-item",
    "properties": [
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "hasSubmenu",
        "attribute": "has-submenu",
        "type": "boolean"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      }
    ],
    "events": []
  },
  {
    "tagName": "ae-input",
    "properties": [
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string"
      },
      {
        "name": "autocomplete",
        "attribute": "autocomplete",
        "type": "string"
      },
      {
        "name": "clearable",
        "attribute": "clearable",
        "type": "boolean"
      },
      {
        "name": "defaultValue",
        "attribute": "default-value",
        "type": "string"
      },
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "error",
        "attribute": "error",
        "type": "string"
      },
      {
        "name": "helpText",
        "attribute": "help-text",
        "type": "string"
      },
      {
        "name": "label",
        "attribute": "label",
        "type": "string"
      },
      {
        "name": "max",
        "attribute": "max",
        "type": "number"
      },
      {
        "name": "maxlength",
        "attribute": "maxlength",
        "type": "number"
      },
      {
        "name": "min",
        "attribute": "min",
        "type": "number"
      },
      {
        "name": "minlength",
        "attribute": "minlength",
        "type": "number"
      },
      {
        "name": "name",
        "attribute": "name",
        "type": "string"
      },
      {
        "name": "pattern",
        "attribute": "pattern",
        "type": "string"
      },
      {
        "name": "placeholder",
        "attribute": "placeholder",
        "type": "string"
      },
      {
        "name": "readonly",
        "attribute": "readonly",
        "type": "boolean"
      },
      {
        "name": "required",
        "attribute": "required",
        "type": "boolean"
      },
      {
        "name": "step",
        "attribute": "step",
        "type": "number"
      },
      {
        "name": "type",
        "attribute": "type",
        "type": "string"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-input-blur",
        "type": "CustomEvent<void>"
      },
      {
        "name": "ae-input-change",
        "type": "CustomEvent<{value: string}>"
      },
      {
        "name": "ae-input-clear",
        "type": "CustomEvent<void>"
      },
      {
        "name": "ae-input-focus",
        "type": "CustomEvent<void>"
      },
      {
        "name": "ae-input-input",
        "type": "CustomEvent<{value: string}>"
      }
    ]
  },
  {
    "tagName": "ae-menu",
    "properties": [],
    "events": []
  },
  {
    "tagName": "ae-menu-divider",
    "properties": [],
    "events": []
  },
  {
    "tagName": "ae-menu-item",
    "properties": [
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-menu-select",
        "type": "CustomEvent<{value: string}>"
      }
    ]
  },
  {
    "tagName": "ae-menu-section",
    "properties": [
      {
        "name": "title",
        "attribute": "title",
        "type": "string"
      }
    ],
    "events": []
  },
  {
    "tagName": "ae-menu-separator",
    "properties": [],
    "events": []
  },
  {
    "tagName": "ae-modal",
    "properties": [
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string | null"
      },
      {
        "name": "backdrop",
        "attribute": "backdrop",
        "type": "boolean"
      },
      {
        "name": "closable",
        "attribute": "closable",
        "type": "boolean"
      },
      {
        "name": "open",
        "attribute": "open",
        "type": "boolean"
      },
      {
        "name": "size",
        "attribute": "size",
        "type": "'small' | 'medium' | 'large'"
      }
    ],
    "events": [
      {
        "name": "ae-modal-close",
        "type": "CustomEvent"
      },
      {
        "name": "ae-modal-open",
        "type": "CustomEvent"
      }
    ]
  },
  {
    "tagName": "ae-pagination",
    "properties": [
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string"
      },
      {
        "name": "currentPage",
        "attribute": "current-page",
        "type": "number"
      },
      {
        "name": "showFirstLast",
        "attribute": "show-first-last",
        "type": "boolean"
      },
      {
        "name": "showPrevNext",
        "attribute": "show-prev-next",
        "type": "boolean"
      },
      {
        "name": "siblingCount",
        "attribute": "sibling-count",
        "type": "number"
      },
      {
        "name": "size",
        "attribute": "size",
        "type": "string"
      },
      {
        "name": "totalPages",
        "attribute": "total-pages",
        "type": "number"
      }
    ],
    "events": [
      {
        "name": "ae-page-change",
        "type": "CustomEvent<{page: number}>"
      }
    ]
  },
  {
    "tagName": "ae-popover",
    "properties": [
      {
        "name": "arrow",
        "attribute": "arrow",
        "type": "boolean"
      },
      {
        "name": "closeOnClickOutside",
        "attribute": "close-on-click-outside",
        "type": "boolean"
      },
      {
        "name": "offset",
        "attribute": "offset",
        "type": "number"
      },
      {
        "name": "open",
        "attribute": "open",
        "type": "boolean"
      },
      {
        "name": "placement",
        "attribute": "placement",
        "type": "string"
      },
      {
        "name": "trigger",
        "attribute": "trigger",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-popover-close",
        "type": "CustomEvent<void>"
      },
      {
        "name": "ae-popover-open",
        "type": "CustomEvent<void>"
      }
    ]
  },
  {
    "tagName": "ae-progress",
    "properties": [
      {
        "name": "animated",
        "attribute": "animated",
        "type": "boolean"
      },
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string"
      },
      {
        "name": "indeterminate",
        "attribute": "indeterminate",
        "type": "boolean"
      },
      {
        "name": "label",
        "attribute": "label",
        "type": "string"
      },
      {
        "name": "max",
        "attribute": "max",
        "type": "number"
      },
      {
        "name": "showLabel",
        "attribute": "show-label",
        "type": "boolean"
      },
      {
        "name": "size",
        "attribute": "size",
        "type": "string"
      },
      {
        "name": "striped",
        "attribute": "striped",
        "type": "boolean"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "number"
      },
      {
        "name": "variant",
        "attribute": "variant",
        "type": "string"
      }
    ],
    "events": []
  },
  {
    "tagName": "ae-radio",
    "properties": [
      {
        "name": "checked",
        "attribute": "checked",
        "type": "boolean"
      },
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "name",
        "attribute": "name",
        "type": "string"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-radio-change",
        "type": "CustomEvent<{checked: boolean, value: string}>"
      }
    ]
  },
  {
    "tagName": "ae-radio-group",
    "properties": [
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "name",
        "attribute": "name",
        "type": "string"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-radio-group-change",
        "type": "CustomEvent<{value: string}>"
      }
    ]
  },
  {
    "tagName": "ae-select",
    "properties": [
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string"
      },
      {
        "name": "defaultValue",
        "attribute": "default-value",
        "type": "string"
      },
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "error",
        "attribute": "error",
        "type": "string"
      },
      {
        "name": "helpText",
        "attribute": "help-text",
        "type": "string"
      },
      {
        "name": "label",
        "attribute": "label",
        "type": "string"
      },
      {
        "name": "multiple",
        "attribute": "multiple",
        "type": "boolean"
      },
      {
        "name": "name",
        "attribute": "name",
        "type": "string"
      },
      {
        "name": "options",
        "attribute": "options",
        "type": "SelectOption[]"
      },
      {
        "name": "placeholder",
        "attribute": "placeholder",
        "type": "string"
      },
      {
        "name": "required",
        "attribute": "required",
        "type": "boolean"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      },
      {
        "name": "values",
        "attribute": "values",
        "type": "string[]"
      }
    ],
    "events": [
      {
        "name": "ae-select-change",
        "type": "CustomEvent<{value: string | string[]}>"
      }
    ]
  },
  {
    "tagName": "ae-spinner",
    "properties": [
      {
        "name": "label",
        "attribute": "label",
        "type": "string"
      },
      {
        "name": "size",
        "attribute": "size",
        "type": "string"
      },
      {
        "name": "variant",
        "attribute": "variant",
        "type": "string"
      }
    ],
    "events": []
  },
  {
    "tagName": "ae-switch",
    "properties": [
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string"
      },
      {
        "name": "checked",
        "attribute": "checked",
        "type": "boolean"
      },
      {
        "name": "defaultChecked",
        "attribute": "default-checked",
        "type": "boolean"
      },
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "name",
        "attribute": "name",
        "type": "string"
      },
      {
        "name": "required",
        "attribute": "required",
        "type": "boolean"
      },
      {
        "name": "size",
        "attribute": "size",
        "type": "string"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-switch-change",
        "type": "CustomEvent<{checked: boolean}>"
      }
    ]
  },
  {
    "tagName": "ae-tab",
    "properties": [
      {
        "name": "ariaControls",
        "attribute": "aria-controls",
        "type": "string"
      },
      {
        "name": "ariaSelected",
        "attribute": "aria-selected",
        "type": "string"
      },
      {
        "name": "id",
        "attribute": "id",
        "type": "string"
      },
      {
        "name": "internalTabIndex",
        "attribute": "data-tabindex",
        "type": "number"
      }
    ],
    "events": []
  },
  {
    "tagName": "ae-tab-panel",
    "properties": [
      {
        "name": "ariaLabelledby",
        "attribute": "aria-labelledby",
        "type": "string"
      },
      {
        "name": "hidden",
        "attribute": "hidden",
        "type": "boolean"
      },
      {
        "name": "id",
        "attribute": "id",
        "type": "string"
      }
    ],
    "events": []
  },
  {
    "tagName": "ae-tabs",
    "properties": [
      {
        "name": "activation",
        "attribute": "activation",
        "type": "'auto' | 'manual'"
      },
      {
        "name": "label",
        "attribute": "label",
        "type": "string"
      },
      {
        "name": "orientation",
        "attribute": "orientation",
        "type": "'horizontal' | 'vertical'"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-tab-change",
        "type": "CustomEvent<{tab: string}>"
      }
    ]
  },
  {
    "tagName": "ae-textarea",
    "properties": [
      {
        "name": "ariaLabel",
        "attribute": "aria-label",
        "type": "string"
      },
      {
        "name": "autoResize",
        "attribute": "auto-resize",
        "type": "boolean"
      },
      {
        "name": "defaultValue",
        "attribute": "default-value",
        "type": "string"
      },
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "error",
        "attribute": "error",
        "type": "string"
      },
      {
        "name": "helpText",
        "attribute": "help-text",
        "type": "string"
      },
      {
        "name": "label",
        "attribute": "label",
        "type": "string"
      },
      {
        "name": "maxlength",
        "attribute": "maxlength",
        "type": "number"
      },
      {
        "name": "minlength",
        "attribute": "minlength",
        "type": "number"
      },
      {
        "name": "name",
        "attribute": "name",
        "type": "string"
      },
      {
        "name": "placeholder",
        "attribute": "placeholder",
        "type": "string"
      },
      {
        "name": "readonly",
        "attribute": "readonly",
        "type": "boolean"
      },
      {
        "name": "required",
        "attribute": "required",
        "type": "boolean"
      },
      {
        "name": "resize",
        "attribute": "resize",
        "type": "'none'|'vertical'|'horizontal'|'both'"
      },
      {
        "name": "rows",
        "attribute": "rows",
        "type": "number"
      },
      {
        "name": "showCount",
        "attribute": "show-count",
        "type": "boolean"
      },
      {
        "name": "value",
        "attribute": "value",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-textarea-blur",
        "type": "CustomEvent<void>"
      },
      {
        "name": "ae-textarea-change",
        "type": "CustomEvent<{value: string}>"
      },
      {
        "name": "ae-textarea-focus",
        "type": "CustomEvent<void>"
      },
      {
        "name": "ae-textarea-input",
        "type": "CustomEvent<{value: string}>"
      }
    ]
  },
  {
    "tagName": "ae-toast",
    "properties": [
      {
        "name": "duration",
        "attribute": "duration",
        "type": "number"
      },
      {
        "name": "message",
        "attribute": "message",
        "type": "string"
      },
      {
        "name": "open",
        "attribute": "open",
        "type": "boolean"
      },
      {
        "name": "pauseOnHover",
        "attribute": "pauseOnHover",
        "type": "boolean"
      },
      {
        "name": "placement",
        "attribute": "placement",
        "type": "'top-right' | 'bottom-right' | 'top-left' | 'bottom-left'"
      },
      {
        "name": "size",
        "attribute": "size",
        "type": "'sm' | 'md' | 'lg'"
      },
      {
        "name": "variant",
        "attribute": "variant",
        "type": "'info' | 'success' | 'warning' | 'error'"
      }
    ],
    "events": [
      {
        "name": "ae-click",
        "type": "CustomEvent"
      },
      {
        "name": "ae-close",
        "type": "CustomEvent"
      }
    ]
  },
  {
    "tagName": "ae-tooltip",
    "properties": [
      {
        "name": "animation",
        "attribute": "animation",
        "type": "'fade' | 'scale'"
      },
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "hideDelay",
        "attribute": "hide-delay",
        "type": "number"
      },
      {
        "name": "hoverDelay",
        "attribute": "hover-delay",
        "type": "number"
      },
      {
        "name": "open",
        "attribute": "open",
        "type": "boolean"
      },
      {
        "name": "placement",
        "attribute": "placement",
        "type": "| 'top'\n  | 'top-start'\n  | 'top-end'\n  | 'bottom'\n  | 'bottom-start'\n  | 'bottom-end'\n  | 'left'\n  | 'left-start'\n  | 'left-end'\n  | 'right'\n  | 'right-start'\n  | 'right-end'"
      },
      {
        "name": "showArrow",
        "attribute": "show-arrow",
        "type": "boolean"
      },
      {
        "name": "strategy",
        "attribute": "strategy",
        "type": "'absolute' | 'fixed'"
      },
      {
        "name": "text",
        "attribute": "text",
        "type": "string"
      }
    ],
    "events": [
      {
        "name": "ae-tooltip-hide",
        "type": "CustomEvent<unknown>"
      },
      {
        "name": "ae-tooltip-show",
        "type": "CustomEvent<unknown>"
      }
    ]
  },
  {
    "tagName": "ae-tree-item",
    "properties": [
      {
        "name": "disabled",
        "attribute": "disabled",
        "type": "boolean"
      },
      {
        "name": "expanded",
        "attribute": "expanded",
        "type": "boolean"
      },
      {
        "name": "label",
        "attribute": "label",
        "type": "string"
      },
      {
        "name": "lazy",
        "attribute": "lazy",
        "type": "boolean"
      },
      {
        "name": "selected",
        "attribute": "selected",
        "type": "boolean"
      }
    ],
    "events": [
      {
        "name": "ae-tree-item-collapse",
        "type": "CustomEvent"
      },
      {
        "name": "ae-tree-item-expand",
        "type": "CustomEvent"
      },
      {
        "name": "ae-tree-item-select",
        "type": "CustomEvent"
      }
    ]
  },
  {
    "tagName": "ae-treeview",
    "properties": [
      {
        "name": "data",
        "attribute": "data",
        "type": "TreeNode[]"
      },
      {
        "name": "emptyMessage",
        "attribute": "empty-message",
        "type": "string"
      },
      {
        "name": "expanded",
        "attribute": "expanded",
        "type": "string[]"
      },
      {
        "name": "indentSize",
        "attribute": "indent-size",
        "type": "number"
      },
      {
        "name": "label",
        "attribute": "label",
        "type": "string"
      },
      {
        "name": "loading",
        "attribute": "loading",
        "type": "boolean"
      },
      {
        "name": "selected",
        "attribute": "selected",
        "type": "string[]"
      },
      {
        "name": "selectionMode",
        "attribute": "selection-mode",
        "type": "'single'|'multiple'|'none'"
      }
    ],
    "events": [
      {
        "name": "ae-treeview-expand",
        "type": "CustomEvent<{expanded: string[]}>"
      },
      {
        "name": "ae-treeview-select",
        "type": "CustomEvent<{selected: string[]}>"
      }
    ]
  }
] as const satisfies readonly AgentUiComponentContract[];
