/* AUTO-GENERATED by scripts/generate-agent-artifacts.mjs. */

export const agentUiSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://debug-diary-1.github.io/AetherUI/docs/agent-ui.schema.json",
  "title": "AetherUI Agent Document",
  "description": "A constrained, validated document for rendering AetherUI custom elements.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "version",
    "root"
  ],
  "properties": {
    "version": {
      "const": "1"
    },
    "root": {
      "$ref": "#/$defs/node"
    }
  },
  "$defs": {
    "jsonValue": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "number"
        },
        {
          "type": "boolean"
        },
        {
          "type": "null"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/jsonValue"
          }
        },
        {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/jsonValue"
          }
        }
      ]
    },
    "node": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "component"
      ],
      "properties": {
        "component": {
          "enum": [
            "ae-accordion",
            "ae-accordion-item",
            "ae-alert",
            "ae-autocomplete",
            "ae-badge",
            "ae-breadcrumb",
            "ae-breadcrumb-item",
            "ae-button",
            "ae-checkbox",
            "ae-combo",
            "ae-drawer",
            "ae-dropdown",
            "ae-dropdown-item",
            "ae-input",
            "ae-menu",
            "ae-menu-divider",
            "ae-menu-item",
            "ae-menu-section",
            "ae-menu-separator",
            "ae-modal",
            "ae-pagination",
            "ae-popover",
            "ae-progress",
            "ae-radio",
            "ae-radio-group",
            "ae-select",
            "ae-spinner",
            "ae-switch",
            "ae-tab",
            "ae-tab-panel",
            "ae-tabs",
            "ae-textarea",
            "ae-toast",
            "ae-tooltip",
            "ae-tree-item",
            "ae-treeview"
          ]
        },
        "id": {
          "type": "string"
        },
        "slot": {
          "type": "string"
        },
        "props": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/jsonValue"
          }
        },
        "actions": {
          "type": "object",
          "additionalProperties": {
            "type": "string",
            "minLength": 1
          }
        },
        "children": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "$ref": "#/$defs/node"
              }
            ]
          }
        }
      }
    }
  }
} as const;

export const componentGuide = [
  {
    "tagName": "ae-accordion",
    "description": "A collapsible disclosure component that shows or hides content panels.",
    "slots": [
      {
        "name": "",
        "description": "Default slot for accordion items"
      }
    ]
  },
  {
    "tagName": "ae-accordion-item",
    "description": "An individual collapsible panel within an accordion.",
    "slots": [
      {
        "name": "",
        "description": "Default slot for panel content"
      },
      {
        "name": "header",
        "description": "Content for the accordion header/button"
      }
    ]
  },
  {
    "tagName": "ae-alert",
    "description": "",
    "slots": [
      {
        "name": "",
        "description": "The alert message content"
      },
      {
        "name": "icon",
        "description": "Custom icon that replaces the variant's default icon"
      }
    ]
  },
  {
    "tagName": "ae-autocomplete",
    "description": "Aether UI Autocomplete Component\n\nA text input with dropdown suggestions as users type, helping them quickly\nfind and select from a list of options.",
    "slots": [
      {
        "name": "arrow",
        "description": "Custom template for the dropdown arrow"
      },
      {
        "name": "clear",
        "description": "Custom template for the clear button"
      },
      {
        "name": "no-results",
        "description": "Content shown when no results match"
      },
      {
        "name": "option",
        "description": "Custom template for rendering each option"
      }
    ]
  },
  {
    "tagName": "ae-badge",
    "description": "A badge component for displaying small labels, tags, counts, or status indicators.\nSupports multiple variants, sizes, closable option, dot indicators, and outline styles.",
    "slots": [
      {
        "name": "",
        "description": "The badge content"
      },
      {
        "name": "icon",
        "description": "Optional icon to display before the content"
      }
    ]
  },
  {
    "tagName": "ae-breadcrumb",
    "description": "A breadcrumb navigation component for showing the current page's location in the site hierarchy.",
    "slots": [
      {
        "name": "",
        "description": "The breadcrumb items (ae-breadcrumb-item elements)"
      }
    ]
  },
  {
    "tagName": "ae-breadcrumb-item",
    "description": "A breadcrumb item component to be used within ae-breadcrumb.",
    "slots": [
      {
        "name": "",
        "description": "The breadcrumb item content"
      }
    ]
  },
  {
    "tagName": "ae-button",
    "description": "Primary action trigger with variants (primary, secondary, ghost, icon‑only) and sizes (sm, md, lg).",
    "slots": [
      {
        "name": "",
        "description": "Button label text (default slot)"
      },
      {
        "name": "icon",
        "description": "Icon content (SVG or other icon element)"
      }
    ]
  },
  {
    "tagName": "ae-checkbox",
    "description": "A checkbox input component with support for checked, unchecked, and indeterminate states.\nParticipates in native form submission via ElementInternals API.",
    "slots": [
      {
        "name": "",
        "description": "The checkbox label content"
      }
    ]
  },
  {
    "tagName": "ae-combo",
    "description": "Aether UI Combobox Component\n\nAn autocomplete dropdown that allows free-text input or selection\nfrom a filtered list, following the ARIA Listbox Combobox pattern.",
    "slots": [
      {
        "name": "",
        "description": "Default slot (not used)"
      }
    ]
  },
  {
    "tagName": "ae-drawer",
    "description": "A drawer component that slides in from the edge of the screen.",
    "slots": [
      {
        "name": "",
        "description": "The drawer body content"
      },
      {
        "name": "footer",
        "description": "The drawer footer content"
      },
      {
        "name": "header",
        "description": "The drawer header content"
      }
    ]
  },
  {
    "tagName": "ae-dropdown",
    "description": "Dropdown menu component",
    "slots": []
  },
  {
    "tagName": "ae-dropdown-item",
    "description": "",
    "slots": []
  },
  {
    "tagName": "ae-input",
    "description": "A text input component with support for various input types, validation, and form participation.\nParticipates in native form submission via ElementInternals API.\nEnabled, named inputs submit empty strings. Validity follows changes to native constraints.",
    "slots": [
      {
        "name": "prefix",
        "description": "Content to display before the input"
      },
      {
        "name": "suffix",
        "description": "Content to display after the input"
      }
    ]
  },
  {
    "tagName": "ae-menu",
    "description": "A menu container component for grouping menu items.",
    "slots": [
      {
        "name": "",
        "description": "The menu items (ae-menu-item elements)"
      }
    ]
  },
  {
    "tagName": "ae-menu-divider",
    "description": "A menu divider component for separating menu items.",
    "slots": []
  },
  {
    "tagName": "ae-menu-item",
    "description": "A menu item component to be used within ae-menu.",
    "slots": [
      {
        "name": "",
        "description": "The menu item content"
      },
      {
        "name": "prefix",
        "description": "Content to display before the menu item text"
      },
      {
        "name": "suffix",
        "description": "Content to display after the menu item text"
      }
    ]
  },
  {
    "tagName": "ae-menu-section",
    "description": "",
    "slots": []
  },
  {
    "tagName": "ae-menu-separator",
    "description": "",
    "slots": []
  },
  {
    "tagName": "ae-modal",
    "description": "A modal dialog component with backdrop, focus management, and accessibility features.",
    "slots": [
      {
        "name": "body",
        "description": "The modal body content"
      },
      {
        "name": "footer",
        "description": "The modal footer content (typically action buttons)"
      },
      {
        "name": "header",
        "description": "The modal header content"
      }
    ]
  },
  {
    "tagName": "ae-pagination",
    "description": "A pagination component for navigating through pages of content.",
    "slots": []
  },
  {
    "tagName": "ae-popover",
    "description": "A popover component for displaying floating content relative to a trigger element.",
    "slots": [
      {
        "name": "",
        "description": "The popover content"
      },
      {
        "name": "trigger",
        "description": "The trigger element"
      }
    ]
  },
  {
    "tagName": "ae-progress",
    "description": "A progress indicator component for showing task completion or loading states.",
    "slots": []
  },
  {
    "tagName": "ae-radio",
    "description": "A radio button input component that participates in native form submission.\nShould be used within an ae-radio-group for proper grouping.",
    "slots": [
      {
        "name": "",
        "description": "The radio label content"
      }
    ]
  },
  {
    "tagName": "ae-radio-group",
    "description": "A container component that manages a group of radio buttons and their selection state.",
    "slots": [
      {
        "name": "",
        "description": "The radio buttons (ae-radio elements) to be grouped"
      }
    ]
  },
  {
    "tagName": "ae-select",
    "description": "A select dropdown component with support for single/multiple selection and form participation.\nParticipates in native form submission via ElementInternals API.",
    "slots": [
      {
        "name": "",
        "description": "The select options (ae-option elements)"
      }
    ]
  },
  {
    "tagName": "ae-spinner",
    "description": "A loading spinner component for indicating loading or processing states.",
    "slots": []
  },
  {
    "tagName": "ae-switch",
    "description": "A toggle switch component for boolean on/off states.\nParticipates in native form submission via ElementInternals API.",
    "slots": [
      {
        "name": "",
        "description": "The switch label content"
      }
    ]
  },
  {
    "tagName": "ae-tab",
    "description": "",
    "slots": []
  },
  {
    "tagName": "ae-tab-panel",
    "description": "",
    "slots": []
  },
  {
    "tagName": "ae-tabs",
    "description": "A tabbed interface component with keyboard navigation and ARIA compliant behavior.",
    "slots": [
      {
        "name": "panel",
        "description": "The panel elements (ae-tab-panel)"
      },
      {
        "name": "tab",
        "description": "The tab elements (ae-tab)"
      }
    ]
  },
  {
    "tagName": "ae-textarea",
    "description": "A textarea component with support for auto-resize, character counting, and form participation.\nParticipates in native form submission via ElementInternals API.\nEnabled, named textareas submit empty strings.",
    "slots": []
  },
  {
    "tagName": "ae-toast",
    "description": "",
    "slots": [
      {
        "name": "",
        "description": "Default slot for the message content"
      },
      {
        "name": "icon",
        "description": "Custom icon"
      }
    ]
  },
  {
    "tagName": "ae-tooltip",
    "description": "A lightweight tooltip component that shows contextual information on hover/focus",
    "slots": [
      {
        "name": "",
        "description": "Default slot for the anchor element that triggers the tooltip"
      }
    ]
  },
  {
    "tagName": "ae-tree-item",
    "description": "",
    "slots": [
      {
        "name": "",
        "description": "The default slot for nested tree items"
      },
      {
        "name": "icon",
        "description": "Custom icon to display before the label"
      }
    ]
  },
  {
    "tagName": "ae-treeview",
    "description": "",
    "slots": [
      {
        "name": "",
        "description": "Default slot for ae-tree-item elements (slot-based mode)"
      }
    ]
  }
] as const;
