name: PR Commands

on:
  issue_comment:
    types: [created]

jobs:
  commands:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/nx') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
          run_install: false
      
      - name: Get PR branch
        uses: actions/github-script@v6
        id: get-pr
        with:
          script: |
            const response = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return response.data.head.ref;
          result-encoding: string
          
      - name: Checkout PR branch
        run: git checkout ${{ steps.get-pr.outputs.result }}
        
      - name: Install dependencies
        run: pnpm install
        
      - name: Run affected command
        if: ${{ contains(github.event.comment.body, '/nx affected') }}
        run: |
          COMMAND="${{ github.event.comment.body }}"
          COMMAND=${COMMAND#"/nx affected"}
          npx nx affected $COMMAND
        
      - name: Run build command
        if: ${{ contains(github.event.comment.body, '/nx build') }}
        run: |
          COMMAND="${{ github.event.comment.body }}"
          COMMAND=${COMMAND#"/nx build"}
          npx nx build $COMMAND
          
      - name: Run test command
        if: ${{ contains(github.event.comment.body, '/nx test') }}
        run: |
          COMMAND="${{ github.event.comment.body }}"
          COMMAND=${COMMAND#"/nx test"}
          npx nx test $COMMAND
          
      - name: Graph visualization
        if: ${{ contains(github.event.comment.body, '/nx graph') }}
        run: |
          npx nx graph --file=dependency-graph.html
          
      - name: Archive dependency graph
        if: ${{ contains(github.event.comment.body, '/nx graph') }}
        uses: actions/upload-artifact@v4
        with:
          name: dependency-graph
          path: dependency-graph.html